spring:
  kafka:
    template:
      default-topic: __eco_udm_configs
    bootstrap-servers: http://localhost:9092
    schema:
      registry:
        url: http://localhost:8081
      default-schema-file: "schema.avsc"
